### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by czater** [ranesr/SwiftIcons#12]
Can we get swift 4 supp? Now there are a lot of compile errors

**Comment by hsoi** [comment]
@ranesr Thank you for adding Swift 4 support by integrating PR #18 

Will you be able to update the Podspec and submit it to the master Cocoapods repo? Thank you.

**Comment by ranesr** [comment]
@hsoi I have updated the Podspec and released new cocoapod.

**Comment by hsoi** [comment]
Awesome! thank you!
