### ISSUE TITLE
Please add a podspec

### ISSUE THREAD

**Issue by dionc** [ranesr/SwiftIcons#2]

**Comment by ranesr** [comment]
@dionc Please check documentation [here](https://github.com/ranesr/SwiftIcons#cocoapods).

**Comment by ranesr** [comment]
Added Cocoapods support with this [commit](https://github.com/ranesr/SwiftIcons/commit/93522bec4e9b49149e57e3e89d94c0e41869acd7).

**Comment by dionc** [comment]
Awesome! Thanks.
