### ISSUE TITLE
Does not work with swift 3

### ISSUE THREAD

**Issue by yogendrakarekar** [ranesr/SwiftIcons#20]
many of the methods has been renamed
1. NSParagraphStyleAttributeName' has been renamed to 'NSAttributedStringKey.paragraphStyle'
Well there are total 33 methods which has been renamed and hence shows issues for swift 3

**Comment by ranesr** [comment]
`SwiftIcons` now supports Swift 4.

**Comment by KingMathew** [comment]
I resolved adding to pod file ->   pod 'SwiftIcons', '~> 1.5.1'
