### ISSUE TITLE
ionicons rewind misspelt

### ISSUE THREAD

**Issue by VSG24** [ranesr/SwiftIcons#25]
In [ionicons.com](ionicons.com) there are `ion-ios-rewind` and `ion-ios-rewind-outline` icons yet in SwifIcons they are spelled as `iosReward`  and `iosRewardOutline` accordingly. They should be renamed.

**Comment by ranesr** [comment]
Fixed in this [commit](https://github.com/ranesr/SwiftIcons/commit/458eefae27e1b6e7bc9249ff59dfb7da30775fb5).
