### ISSUE TITLE
UIColor extension ambiguous when using Hue

### ISSUE THREAD

**Issue by codefiesta** [ranesr/SwiftIcons#3]
Popular UIColor library Hue uses the UIColor(hex:) constructor in an extension, leading to a conflict with the convenience init in the UIColor extension.

public extension UIColor { convenience init(hex: String) {

Raising the error:

Ambiguous use of init(hex:)
Please remove or consider making Hue a dependency or using a non-conflicting category convenience method?

**Comment by ranesr** [comment]
Just curious, are you using Hue for other functions in your code?

**Comment by codefiesta** [comment]
Yes, we are using the gradient features provided in Hue as well.

**Comment by ranesr** [comment]
Please use the new release [1.3](https://github.com/ranesr/SwiftIcons/releases/tag/1.3). I have removed the convenience method from library.
