### ISSUE TITLE
CocoaPods could not find compatible versions for pod "SwiftIcons": on Xcode 10

### ISSUE THREAD

**Issue by irshadpc** [ranesr/SwiftIcons#43]
Try to install via cocoapods but I have faced compatible issues. I have using  Xcode 10.

[!] CocoaPods could not find compatible versions for pod "SwiftIcons":
  In Podfile:
    SwiftIcons (~> 2.2.0)

None of your spec sources contain a spec satisfying the dependency: `SwiftIcons (~> 2.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by ranesr** [comment]
Can you try using the latest version for SwiftIcons ~> `2.3.0`?

**Comment by irshadpc** [comment]
@ranesr Sure

**Comment by limadeveloper** [comment]
I've got issue when I try pod update: 

`Specs satisfying the `SwiftIcons (~> 2.3)` dependency were found, but they required a higher minimum deployment target.`

I need supporting iOS 11, but the pod spec deployment target is 12.1 in this version (2.3).
@ranesr is it possible to change that?

**Comment by dcarra01** [comment]
Same here, can't update with iOS 10 project.

**Comment by limadeveloper** [comment]
I've a PR opened to fix that

**Comment by ranesr** [comment]
Can you try using the latest version for SwiftIcons ~> `2.3.2`?

**Comment by irshadpc** [comment]
@ranesr I think the issue is resolved.
