### ISSUE TITLE
Update for Swift 4.2

### ISSUE THREAD

**Issue by p0tvin29** [ranesr/SwiftIcons#45]
Will there be an update released that fixes the errors in Swift 4.2?

**Comment by irshadpc** [comment]
It is in the pipeline @p0tvin29

**Comment by ommehaz** [comment]
when, because project failing

**Comment by lawlietop123** [comment]
swift 4.2 + 1

**Comment by anonrig** [comment]
👍

**Comment by ranesr** [comment]
Merged #44
