### ISSUE TITLE
Print initialization method in demo project when clicking an icon

### ISSUE THREAD

**Issue by hstdt** [ranesr/SwiftIcons#5]
For example, when I click  an airplane emoji ,then console prints `UIImage.init(icon: .emoji(.airplane), size: CGSize(width: 35, height: 35))`

I think showing the method is pretty helpful.Thank you!

**Comment by ranesr** [comment]
I have added example usage for all the methods in the demo project with [commit](https://github.com/ranesr/SwiftIcons/commit/961d9af66a86391114089a493f5c2f16ccfaeab2).
