### ISSUE TITLE
Update Podspec

### ISSUE THREAD

**Issue by intellitour** [ranesr/SwiftIcons#63]
The last merged PR (https://github.com/ranesr/SwiftIcons/pull/57) did not update the podspec file. Please, do so.

**Comment by anonrig** [comment]
Yeah, this is a blocking issue for me too. @ranesr

**Comment by AndyDunn** [comment]
I wondered why I wasn't getting the latest version. @ranesr Any chance of updating this?

**Comment by ranesr** [comment]
I released new version 3.0.
