### ISSUE TITLE
UIBarButtonItem is not aligned

### ISSUE THREAD

**Issue by yeralin** [ranesr/SwiftIcons#7]
Hi, I'm using SwiftIcons library (installed though Pod).

I'm trying to create UIBarButtonItem with specific icon.
I set it like this:
`menuButton.setIcon(icon: .ionicons(.navicon),  iconSize: 35, color: systemColor)`
where `systemColor == UIView().tintColor`
But with this setup, my UIBar looks like this:
![image](https://cloud.githubusercontent.com/assets/8620461/26787499/3ac7b34e-49d8-11e7-84a3-ab2c7c8d1960.png)
As, you can see it is not aligned vertically (I tried using `SetTitlePositionAdjustment`, but I can adjust only horizontal position).

I kinda fixed the position by using:
`menuButton.setIcon(prefixText: "", icon: .ionicons(.navicon), iconColor: systemColor, postfixText: "", cgRect: CGRect(x: 30, y: 30, width: 30, height: 30), size: 35, iconSize: 36)`
![image](https://cloud.githubusercontent.com/assets/8620461/26787657/c682f8da-49d8-11e7-9dc9-24b996dba675.png)

But, then button is not tappable...

Can anyone help me here?

**Comment by yeralin** [comment]
@ranesr

**Comment by ranesr** [comment]
Please Check [Release 1.5](https://github.com/ranesr/SwiftIcons/releases/tag/1.5).

**Comment by ranesr** [comment]
I have added Example 3 (Icon with custom cgRect) in [README](https://github.com/ranesr/SwiftIcons#uibarbuttonitem).

**Comment by yeralin** [comment]
@ranesr thank you :) I was already trying to fix myself. You were faster :D

**Comment by yeralin** [comment]
We gotta little problem here.
Since it is a custom button, with your new change fading effect on button press is gone now.
I was able to fix it by modifying function like this:
`
public func setIcon(icon: FontType, iconSize: CGFloat, color: UIColor = .black, cgRect: CGRect, target: AnyObject?, action: Selector) {
        
        title = nil
        let button = UIButton(frame: cgRect)
        let onPressColor = color.withAlphaComponent(0.4)
        button.setIcon(icon: icon, iconSize: iconSize, color: color, forState: .normal)
        button.addTarget(target, action: action, for: .touchUpInside)
        button.setTitleColor(onPressColor, for: .highlighted)
        
        customView = button
    }
`

If you approve, I will create a PR
